### ISSUE TITLE
Add some validation to catch null/undefined hostnames

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/did-io#27]
Default settings in bedrock-did-client set the hostname to 'null' which can get passed into did-io here:

https://github.com/digitalbazaar/bedrock-did-client/blob/did-io-0.7.x/lib/index.js#L35

This results in an error thrown out of this module:
```
Could not fetch ledger agents: { FetchError: request to https://null/ledger-agents failed, reason: getaddrinfo ENOTFOUND null null:443
    at ClientRequest.<anonymous> (/home/matt/dev/bedrock-dev/bedrock-ledger-validator-signature/test/node_modules/node-fetch/lib/index.js:1345:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://null/ledger-agents failed, reason: getaddrinfo ENOTFOUND null null:443',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
```

There should be some validation of the hostname before attempting to connect to `https://null`

If `mode` and `did` should be validated as well if they aren't already.

**Comment by dmitrizagidulin** [comment]
Thanks!

**Comment by dmitrizagidulin** [comment]
This will be addressed by PRs https://github.com/digitalbazaar/web-ledger-client/pull/4 and https://github.com/digitalbazaar/did-io/pull/28

**Comment by dmitrizagidulin** [comment]
Fixed in latest `development`, closing.
